[tools]
deno = "latest"
hk = "latest"
pkl = "latest"

[tasks.publish]
description = "Publish to JSR (Run from GitHub Actions)"
run = [
    """jq '.version = "{{option(name='version')}}"' deno.jsonc > tmp.json && mv tmp.json deno.jsonc""",
    "npx jsr publish --allow-dirty",
]
